server:
  port: 9001
  error:
    include-stacktrace: ALWAYS
  servlet:
    context-path:
    session:
      cookie:
        same-site: None
        secure: true
spring:
  application:
    name: auth-service
  output:
    ansi:
      enabled: ${JSSO_ANSI_ENABLED:ALWAYS}
  mvc:
    static-path-pattern: /static/**
    cors:
      configs:
        - pattern: /**
          allowed-origins: ${CORS_ALLOWED_ORIGINS:http://127.0.0.1:8181,http://localhost:8181,http://192.168.0.150:8181}
          allowed-headers: "*"
          exposed-headers: ${spring.security.oauth2.authorizationserver.custom-handler-header-name}
          allowed-methods: "*"
          allow-credentials: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  data:
    redis:
      client-type: lettuce
      database: ${REDIS_DB:0}
      host: ${REDIS_HOST:redis-auth}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:qwerty12345678}
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
  liquibase:
    enabled: true
    change-log: classpath:database/db.changelog.yaml
    contexts: prod, dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres-auth:5432/auth_db}
    username: ${POSTGRES_USER_AUTH:postgres}
    password: ${POSTGRES_PASSWORD_AUTH:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      connection-test-query: select 1
      maximum-pool-size: 10
      minimum-idle: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      pool-name: "HikariPool-j-sso"
      register-mbeans: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  web:
    resources:
      static-locations: classpath:static
  session:
    timeout: 1800
    redis:
      flush-mode: on_save
      namespace: j-sso:session
      save-mode: on_set_attribute
  task:
    scheduling:
      pool:
        size: 2
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            required: true
            emable: true
  cloud:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: sso-client
          client-secret: sso-client
          introspection-uri: http://auth-service:9001/oauth2/token-info
      authorizationserver:
        issuer-url: http://auth-service:9001${server.servlet.context-path}
        introspection-endpoint: /oauth2/token-info
        reset-password-endpoint: /client/auth/reset-password
        authentication-success-url: ${AUTH_SERVICE_DOMAIN:http://localhost:8181}/client/oauth/continue
        saved-request-url-starts-with: ${AUTH_SERVICE_DOMAIN:http://localhost:9001}${server.servlet.context-path}/oauth2/authorize
        custom-handler-header-name: J-Sso-Next-Location
        authorization-ttl: 10800000
        authorization-consent-ttl: 10800000
      client:
        registration:
#          azure:
#            provider: azure
#            client-id: ${AZURE_CLIENT_ID}
#            client-secret: ${AZURE_CLIENT_SECRET}
#            scope:
#              - openid
#              - profile
#              - email
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${AUTH_SERVICE_DOMAIN:http://localhost:8181}/login/oauth2/code/github

          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${AUTH_SERVICE_DOMAIN:http://localhost:8181}/login/oauth2/code/google
            scope:
              - email
              - profile

          yandex:
            provider: yandex
            clientId: ${YANDEX_CLIENT_ID}
            clientSecret: ${YANDEX_CLIENT_SECRET}
            redirect-uri: ${AUTH_SERVICE_DOMAIN:http://localhost:8181}/login/oauth2/code/yandex
            authorizationGrantType: authorization_code
            clientName: Yandex

        provider:
          #          azure:
          #            issuer-uri: https://login.microsoftonline.com/<your creadentails>/v2.0
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            userInfoUri: https://login.yandex.ru/info

yandex-avatar-url: https://avatars.yandex.net/get-yapic/{avatarId}/islands-retina-50

otp-store:
  cookie-name: j-sso-temporary-session
  cookie-domain: localhost
  cookie-max-age: 180

file-store:
  base-path: ${AUTH_SERVICE_PATH_STORAGE:~/auth-service-file-store}

scheduled-tasks:
  delete-old-events:
    cron: '@daily'
    saved-period-days: 1
  notify-delete-users:
    cron: '@daily'

rest-clients:
  service-client-connection-timeout: 10000
  service-client-request-timeout: 30000

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
