server:
  port: 9005

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.server: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: j-service-client
          client-secret: j-service-client
          introspection-uri: ${SSO_URL:http://auth-service:9001}/oauth2/token-info
  cloud:
    gateway:
      routes:
        - id: geodata-service
          uri: lb://geodata-service
          predicates:
            - Path=/api/geodata/**

        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/api/documents/**

        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/search/**

      httpserver:
        wiretap: true
      httpclient:
        wiretap: true

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://127.0.0.1:8080, http://212.42.112.36:8080"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true