server:
  port: 9004

spring:
  application:
    name: search-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:elasticsearch:9200}
    connection-timeout: 2s
    socket-timeout: 10s
  auth-types:
    auth-header-enabled: true
    client-credentials-enabled: true
    authorization-code-enabled: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: ${J_SERVICE_CLIENT_ID:j-service-client}
          client-secret: ${J_SERVICE_CLIENT_SECRET:j-service-client}
          introspection-uri: ${SSO_URL:http://auth-service:9001}/oauth2/token-info

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
