server:
  port: 9006

mediamtx:
  api:
    url: http://mediamtx:9997
  hls:
    url: ${MEDIAMTX_HLS_DOMAIN:http://localhost:8888}
    sourceOnDemand: ${MEDIAMTX_SOURCEONDEMAND:true}
    sourceOnDemandCloseAfter: ${MEDIAMTX_SOURCEONDEMANDCLOSEAFTER:20s}
  cleanup:
    rate-ms: ${MEDIAMTX_CLEANUP_RATE:300000}

spring:
  application:
    name: stream-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  auth-types:
    auth-header-enabled: true
    client-credentials-enabled: true
    authorization-code-enabled: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: ${J_SERVICE_CLIENT_ID:j-service-client}
          client-secret: ${J_SERVICE_CLIENT_SECRET:j-service-client}
          introspection-uri: ${SSO_URL:http://auth-service:9001}/oauth2/token-info

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
